name: Issue Auto Commenter

permissions:
  issues: write

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    # event.issue.number # echo '${{ toJson(github) }}' | jq 
    steps:
      - name: Create comment on issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]
  
            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'

  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with API
        run: |
          gh api -X POST \
            /repos/${{ env.ORGANIZATION }}/${{ env.REPOSITORY }}/issues/${{ env.ISSUE_NUMBER }}/comments \
            -f body='This is a multi-line test comment from the API'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.repository_owner }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
